### PR TITLE
Rb ldap

### PR DESCRIPTION
**Pull request by butlerx**
the story of rb-ldap

### CODE REVIEW

**Review by m1cr0man — APPROVED** [review]
LGTM

**Comment by m1cr0man** [comment]
What's wrong with the build on this?

**Comment by butlerx** [comment]
its in strict mode so warnings error and 
```
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead. 
```

**Comment by butlerx** [comment]
outside the scope of this pr

**Comment by theycallmemac** [comment]
What are we doing with this PR now? @butlerx

**Comment by butlerx** [comment]
it should be merged as is, then be updated with current info since the last edit in a separate pr.  and the lint issue should be fixed in a separate pr.
i would have merged it in Feb but i no longer have write access

**Comment by theycallmemac** [comment]
Thank you for work items, I'll merge this and create an issue after based on them.

**Pull request merged**
