### PR TITLE
Moved bind9 from network to services

### PR DESCRIPTION
**Pull request by VoyTechnology**
This seems like a more appropriate location, as "discussed" in https://github.com/redbrick/docs/issues/7.

### CODE REVIEW

**Comment by VoyTechnology** [comment]
CC @zergless

**Comment by butlerx** [comment]
id rather keep dns in network. services are things we offer, the network should how all our services connect 
which is dns

**Comment by VoyTechnology** [comment]
I would disagree that services are only the things we offer. For example Nagios is for admins, not users. I interpret services as all services, including the ones used for running the infrastructure. Essentially it makes no difference between user facing and internal services from management perspective - both need to run.

**Comment by butlerx** [comment]
i wouldnt consider nagios a service id say its section should be moved

**Comment by zergless** [comment]
I would argue bind is a service and should not be in networking.

**Comment by gruunday** [comment]
I would agree. Move to ~~networking~~ services

**Comment by zergless** [comment]
@gruunday can you clarify what you mean pls

**Review by zergless — APPROVED** [review]

**Review by gruunday — APPROVED** [review]

**Pull request merged**
