### PR TITLE
Removed the section on deployment as its no longer up to date

### PR DESCRIPTION
**Pull request by VoyTechnology**

### CODE REVIEW

**Review by butlerx — CHANGES_REQUESTED** [review]
Want to add in how docs.rb is done too

**Comment by VoyTechnology** [comment]
Separate PR?

**Comment by butlerx** [comment]
It's only an extra line. 
Hourly cron pulls git if there are changes it rebuilds

**Comment by VoyTechnology** [comment]
Will resolve #33

**Comment by VoyTechnology** [comment]
Is there a script that detects if there are changes? Should we also add that (if it exists)

**Comment by butlerx** [comment]
No just git pull && mkdocs build

**Review by butlerx — APPROVED** [review]

**Pull request merged**
