### PR TITLE
update monitoring docs

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Comment by butlerx** [comment]
plz don't merge this yet want to add links to external resources

**Review by theycallmemac — DISMISSED** [review]
Looks good, some capitalisation missing here and there but nothing that really makes it harder to read. Good job documenting this.

**Comment by theycallmemac** [comment]
I can review again once you add external links :)

**Comment by butlerx** [comment]
Im happy with this pr now had to delete some files and fix circleci  aswell

**Comment by butlerx** [comment]
close #2

**Review by theycallmemac — APPROVED** [review]

**Pull request merged**
